'use strict';

const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const test = require('node:test');
const { createCryptoVendorSource } = require('../scripts/crypto-bundle.js');

const projectRoot = path.resolve(__dirname, '..');
const slip39Source = fs.readFileSync(path.join(projectRoot, 'src', 'cold', 'slip39.js'), 'utf8');

function createContext(options = {}) {
  const context = {
    ArrayBuffer,
    TextDecoder,
    TextEncoder,
    Uint8Array,
    WebAssembly,
    atob,
    crypto: options.cryptoObject || crypto.webcrypto,
    console
  };
  context.window = context;
  context.self = context;
  vm.runInNewContext(createCryptoVendorSource(projectRoot), context);
  vm.runInNewContext(slip39Source, context, { filename: 'src/cold/slip39.js' });
  return context;
}

function bytes(value) {
  return Uint8Array.from(Buffer.from(value, 'hex'));
}

function hex(value) {
  return Buffer.from(value).toString('hex');
}

// Independent fixtures from Trezor's published python-shamir-mnemonic
// vectors.json, not values generated by this implementation:
// https://github.com/trezor/python-shamir-mnemonic/blob/master/vectors.json
const VECTOR_1 = [
  'duckling enlarge academic academic agency result length solution fridge kidney coal piece deal husband erode duke ajar critical decision keyboard'
];
const VECTOR_4 = [
  'shadow pistol academic always adequate wildlife fancy gross oasis cylinder mustang wrist rescue view short owner flip making coding armed',
  'shadow pistol academic acid actress prayer class unknown daughter sweater depict flip twice unkind craft early superior advocate guest smoking'
];
const VECTOR_17 = [
  'eraser senior decision roster beard treat identify grumpy salt index fake aviation theater cubic bike cause research dragon emphasis counter',
  'eraser senior ceramic snake clay various huge numb argue hesitate auction category timber browser greatest hanger petition script leaf pickup',
  'eraser senior ceramic shaft dynamic become junior wrist silver peasant force math alto coal amazing segment yelp velvet image paces',
  'eraser senior ceramic round column hawk trust auction smug shame alive greatest sheriff living perfect corner chest sled fumes adequate',
  'eraser senior decision smug corner ruin rescue cubic angel tackle skin skunk program roster trash rumor slush angel flea amazing'
];
const VECTOR_43 = [
  'enemy favorite academic acid cowboy phrase havoc level response walnut budget painting inside trash adjust froth kitchen learn tidy punish',
  'enemy favorite academic always academic sniff script carpet romp kind promise scatter center unfair training emphasis evening belong fake enforce'
];
const VECTOR_45 = [
  'western apart academic always artist resident briefing sugar woman oven coding club ajar merit pecan answer prisoner artist fraction amount desktop mild false necklace muscle photo wealthy alpha category unwrap spew losing making',
  'western apart academic acid answer ancient auction flip image penalty oasis beaver multiple thunder problem switch alive heat inherit superior teaspoon explain blanket pencil numb lend punish endless aunt garlic humidity kidney observe'
];

test('SLIP-39 validates and recovers the official 128-bit no-sharing vector', () => {
  const slip39 = createContext().__coldboxSlip39;
  assert.equal(slip39.validate(VECTOR_1[0]), true);
  assert.equal(hex(slip39.recover(VECTOR_1, 'TREZOR')), 'bb54aac4b89dc868ba37d9cc21b2cece');
  assert.equal(slip39.validate(VECTOR_1[0].replace(/keyboard$/, 'kidney')), false);
});

test('SLIP-39 validates and recovers the official 256-bit extendable vector used by vault recovery', () => {
  const slip39 = createContext().__coldboxSlip39;
  assert.equal(slip39.validate(VECTOR_45[0]), true);
  assert.equal(slip39.validate(VECTOR_45[1]), true);
  assert.equal(
    hex(slip39.recover(VECTOR_45, 'TREZOR')),
    '8dc652d6d6cd370d8c963141f6d79ba440300f25c467302c1d966bff8f62300d'
  );
  const decoded = slip39.decode(VECTOR_45[0]);
  assert.equal(decoded.identifier, 32065);
  assert.equal(decoded.extendableBackupFlag, 1);
  assert.equal(decoded.iterationExponent, 0);
  assert.equal(decoded.groupIndex, 0);
  assert.equal(decoded.groupThreshold, 1);
  assert.equal(decoded.groupCount, 1);
  assert.equal(decoded.memberIndex, 2);
  assert.equal(decoded.memberThreshold, 2);
  assert.equal(decoded.share.length, 32);
});

test('SLIP-39 recovers an independent 2-of-3 vector and refuses one share', () => {
  const slip39 = createContext().__coldboxSlip39;
  assert.equal(hex(slip39.recover(VECTOR_4, 'TREZOR')), 'b43ceb7e57a0ea8766221624d01b0864');
  assert.throws(() => slip39.recover([VECTOR_4[0]]), /2/);
});

test('SLIP-39 handles the official two-level group vector', () => {
  const slip39 = createContext().__coldboxSlip39;
  assert.equal(hex(slip39.recover(VECTOR_17, 'TREZOR')), '7c3397a292a5941682d7a4ae2d898d11');
});

test('SLIP-39 handles the extendable-backup vector', () => {
  const slip39 = createContext().__coldboxSlip39;
  assert.equal(hex(slip39.recover(VECTOR_43, 'TREZOR')), '48b1a4b80b8c209ad42c33672bdaa428');
  assert.equal(slip39.decode(VECTOR_43[0]).extendableBackupFlag, 1);
});

test('SLIP-39 generation uses secure randomness, round-trips, and supports a passphrase', () => {
  const slip39 = createContext().__coldboxSlip39;
  const secret = bytes('00112233445566778899aabbccddeeff');
  const generated = slip39.generate(secret, {
    identifier: 7,
    groups: [{ threshold: 2, count: 3 }],
    passphrase: 'correct horse',
    extendableBackupFlag: 1
  });
  assert.equal(generated.shares.length, 3);
  assert.equal(generated.shares.every((share) => slip39.validate(share.mnemonic)), true);
  assert.equal(hex(slip39.recover([generated.shares[0].mnemonic, generated.shares[2].mnemonic], 'correct horse')), '00112233445566778899aabbccddeeff');
  assert.notEqual(hex(slip39.recover([generated.shares[0].mnemonic, generated.shares[2].mnemonic], 'wrong horse')), hex(secret));
});

test('SLIP-39 emits the standard 20-word and 33-word share lengths', () => {
  const slip39 = createContext().__coldboxSlip39;
  const generated128 = slip39.generate(new Uint8Array(16), {
    identifier: 8,
    groups: [{ threshold: 2, count: 3 }]
  });
  const generated256 = slip39.generate(new Uint8Array(32), {
    identifier: 9,
    groups: [{ threshold: 2, count: 3 }]
  });
  assert.equal(generated128.shares.every((share) => share.mnemonic.split(' ').length === 20), true);
  assert.equal(generated256.shares.every((share) => share.mnemonic.split(' ').length === 33), true);
  assert.throws(() => slip39.generate(new Uint8Array(16), { passphrase: 'line\nfeed' }), /printable ASCII/);
});

test('SLIP-39 refuses generation when crypto.getRandomValues is unavailable', () => {
  const slip39 = createContext({ cryptoObject: {} }).__coldboxSlip39;
  assert.throws(() => slip39.generate(new Uint8Array(16)), /getRandomValues/);
});

test('SLIP-39 rejects malformed metadata, mixed sets, duplicate members, and invalid secret sizes', () => {
  const slip39 = createContext().__coldboxSlip39;
  assert.equal(slip39.validate(VECTOR_1[0].replace(/^duckling/, 'not-a-word')), false);
  assert.equal(slip39.validate(VECTOR_1[0].replace(/keyboard$/, 'kidney')), false);
  assert.throws(() => slip39.recover([VECTOR_4[0].replace(/^shadow/, 'not-a-word')]), /share 1/i);
  assert.throws(() => slip39.generate(new Uint8Array(15)), /16 to 64/);
  assert.throws(() => slip39.generate(new Uint8Array(17)), /even length/);
  assert.throws(() => slip39.recover([VECTOR_4[0], VECTOR_1[0]]), /same|group|checksum/i);
  assert.throws(() => slip39.recover([VECTOR_4[0], VECTOR_4[0]]), /member|same|duplicate|repeats/i);
});
